name: Release Tests

on:
  release:
    types: [ published, created ]

jobs:
  comprehensive-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Run all tests
      run: |
        cd bhopengraph/tests
        python run_tests.py

    - name: Run tests with verbose output
      run: |
        cd bhopengraph/tests
        python -m unittest discover -v

    - name: Run tests with coverage
      run: |
        pip install coverage
        coverage run --source=bhopengraph bhopengraph/tests/run_tests.py
        coverage report

  build-package:
    runs-on: ubuntu-latest
    needs: comprehensive-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel

    - name: Build package
      run: |
        python -m build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bhopengraph-package
        path: dist/
